Set max queue count for IDPF devices; remove broken virtio logic
This removes the logic which claimed to enable multiqueue for virtio-net
devices, which was bugged and would never actually do anything. The
following expressions effectively mean the code was a no-op:

```sh
if [[ -n "${num_max_channels}" || "${num_max_channels}" -eq "1" ]]; then
  do_nothing
...
if is_decimal_int "$num_max_channels"; then
  do_nothing
...
```

The intended logic hasn't been necessary since
[this commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=4490001029012539937ff02778fe6180613fa949)
(2016), which has the same effect of what this script was *trying* to
do.

For IDPF: It is possible for GCE's control plane to return more queues
than than Linux will
[use by default](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/net/core/dev.c?h=v6.12.81#n3173).

PiperOrigin-RevId: 901390740

diff --git a/src/usr/bin/google_set_multiqueue b/src/usr/bin/google_set_multiqueue
--- a/src/usr/bin/google_set_multiqueue
+++ b/src/usr/bin/google_set_multiqueue
@@ -190,6 +190,16 @@ function is_multinic_accelerator_platform() {
   return 0
 }
 
+# returns 0 (success) if the supplied nic is a VIRTIO device.
+function is_virtio() {
+  local -r nic_name="$1"
+  local -r driver_type=$(ethtool -i $nic_name | grep driver)
+
+  [[ "$driver_type" == *"virtio_net"* ]] || return 1
+
+  return 0
+}
+
 # returns 0 (success) if the supplied nic is a Gvnic device.
 function is_gvnic() {
   local -r nic_name="$1"
@@ -440,31 +450,30 @@ VIRTIO_NET_DEVS=${ROOT_DIR}sys/bus/virtio/drivers/virtio_net/virtio*
 is_multinic_accelerator_platform
 IS_MULTINIC_ACCELERATOR_PLATFORM=$?
 
-# Loop through all the virtionet devices and enable multi-queue
+# Enable max supported queue count for IDPF devices.
 if [ -x "$(command -v ethtool)" ]; then
-  for dev in $VIRTIO_NET_DEVS; do
-    ETH_DEVS=${dev}/net/*
-    for eth_dev in $ETH_DEVS; do
-      eth_dev=$(basename "$eth_dev")
-      if ! errormsg=$(ethtool -l "$eth_dev" 2>&1); then
-        echo "ethtool says that $eth_dev does not support virtionet multiqueue: $errormsg."
-        continue
-      fi
-      num_max_channels=$(ethtool -l "$eth_dev" | grep -m 1 Combined | cut -f2)
-      if [[ -n "${num_max_channels}" || "${num_max_channels}" -eq "1" ]]; then
-        echo "num_max_channels is n/a, skipping set channels for $eth_dev"
-        continue
-      fi
-      if is_decimal_int "$num_max_channels" && \
-        set_channels "$eth_dev" "$num_max_channels"; then
-        echo "Set channels for $eth_dev to $num_max_channels."
-      else
-        echo "Could not set channels for $eth_dev to $num_max_channels."
-      fi
-    done
+  for eth_dev in $(get_pci_network_interfaces); do
+    if ! is_idpf "$eth_dev"; then
+      continue
+    fi
+    if ! errormsg=$(ethtool -l "$eth_dev" 2>&1); then
+      echo "\`ethtool -l\` failed for $eth_dev: $errormsg."
+      continue
+    fi
+    num_max_channels=$(ethtool -l "$eth_dev" | grep -m 1 Combined | cut -f2)
+    if [[ -z "${num_max_channels}" || "${num_max_channels}" -eq "1" ]]; then
+      echo "num_max_channels is n/a, skipping set channels for $eth_dev"
+      continue
+    fi
+    if ! is_decimal_int "$num_max_channels"; then
+      echo "Could not set channels for $eth_dev to $num_max_channels."
+      continue
+    fi
+    set_channels "$eth_dev" "$num_max_channels"
+    echo "Set channels for $eth_dev to $num_max_channels."
   done
 else
-  echo "ethtool not found: cannot configure virtionet multiqueue."
+  echo "ethtool not found: unable to configure device queue counts"
 fi
 
 for dev in $VIRTIO_NET_DEVS
