Removes length limiting on xxd call (now reads to end instead of arbitrarily 256 characters).
Also fixes the following:
  - Various fixes with bash syntax (e.g., unnecessary {} around variable names)
  - Removed some dead code
  - Updated logic for clarity around verifying the device is a PD device

diff --git a/src/lib/udev/google_nvme_id b/src/lib/udev/google_nvme_id
--- a/src/lib/udev/google_nvme_id
+++ b/src/lib/udev/google_nvme_id
@@ -19,15 +19,13 @@
 # Locations of the script's dependencies
 readonly nvme_cli_bin=/usr/sbin/nvme
 
-# Flags to identify the disk type
-readonly LOCAL_SSD="LocalSsd"
-readonly PD="PersistentDisk"
-
+# Bash regex to parse device paths and controller identification
 readonly NAMESPACE_NUMBER_REGEX="/dev/nvme[[:digit:]]+n([[:digit:]]+).*"
 readonly PARTITION_NUMBER_REGEX="/dev/nvme[[:digit:]]+n[[:digit:]]+p([[:digit:]]+)"
+readonly PD_NVME_REGEX="sn[[:space:]]+:[[:space]]+nvme_card-pd"
 
-# Globals used to generate the symlinks for a PD-NVMe disk
-ID_NAMESPACE_INDEX=''
+# Globals used to generate the symlinks for a PD-NVMe disk.  These are populated
+# by the identify_pd_disk function and exported for consumption by udev rules.
 ID_SERIAL=''
 ID_SERIAL_SHORT=''
 
@@ -57,26 +55,26 @@ function err() {
 #######################################
 function get_namespace_device_name() {
   local nvme_json
-  nvme_json="$("${nvme_cli_bin}" id-ns -b "${1}" | xxd -p -seek 384 -l 256 | xxd -p -r)"
-  if [[ $? != 0 ]]; then
+  nvme_json="$("$nvme_cli_bin" id-ns -b "$1" | xxd -p -seek 384 | xxd -p -r)"
+  if [[ $? -ne 0 ]]; then
     return 1
   fi
 
-  if [[ -z "${nvme_json}" ]]; then
+  if [[ -z "$nvme_json" ]]; then
     err "NVMe Vendor Extension disk information not present"
     return 1
   fi
 
   local device_name
-  device_name="$(echo "${nvme_json}" | sed -e 's/.*"device_name":"\([a-zA-Z0-9_-]\+\)".*/\1/g')"
+  device_name="$(echo "$nvme_json" | sed -e 's/.*"device_name":"\([a-zA-Z0-9_-]\+\)".*/\1/g')"
 
   # Error if our device name is empty
-  if [[ -z "${device_name}" ]]; then
+  if [[ -z "$device_name" ]]; then
     err "Empty name"
     return 1
   fi
 
-  echo "${device_name}"
+  echo "$device_name"
   return 0
 }
 
@@ -92,15 +90,15 @@ function get_namespace_device_name() {
 #   0 if the namespace id could be retrieved, 1 otherwise
 #######################################
 function get_namespace_number() {
-  local dev_path="${1}"
+  local dev_path="$1"
   local namespace_number
-  if [[ "${dev_path}" =~ $NAMESPACE_NUMBER_REGEX ]]; then
+  if [[ "$dev_path" =~ $NAMESPACE_NUMBER_REGEX ]]; then
     namespace_number="${BASH_REMATCH[1]}"
   else
     return 1
   fi
 
-  echo "${namespace_number}"
+  echo "$namespace_number"
   return 0
 }
 
@@ -115,11 +113,11 @@ function get_namespace_number() {
 #   no partition.
 #######################################
 function get_partition_number() {
-  local dev_path="${1}"
+  local dev_path="$1"
   local partition_number
-  if [[ "${dev_path}" =~ $PARTITION_NUMBER_REGEX ]]; then
+  if [[ "$dev_path" =~ $PARTITION_NUMBER_REGEX ]]; then
     partition_number="${BASH_REMATCH[1]}"
-    echo "${partition_number}"
+    echo "$partition_number"
   else
     echo ''
   fi
@@ -135,91 +133,38 @@ function get_partition_number() {
 #   The device path for the disk
 #######################################
 function gen_symlink() {
-  local dev_path="${1}"
-  local partition_number="$(get_partition_number "${dev_path}")"
+  local dev_path="$1"
+  local partition_number="$(get_partition_number "$dev_path")"
 
-  if [[ -n "${partition_number}" ]]; then
-    ln -s "${dev_path}" /dev/disk/by-id/google-persistent-disk-"${ID_SERIAL_SHORT}"-part"${partition_number}" > /dev/null 2>&1
+  if [[ -n "$partition_number" ]]; then
+    ln -s "$dev_path" /dev/disk/by-id/google-persistent-disk-"$ID_SERIAL_SHORT"-part"$partition_number" > /dev/null 2>&1
   else
-    ln -s "${dev_path}" /dev/disk/by-id/google-persistent-disk-"${ID_SERIAL_SHORT}" > /dev/null 2>&1
+    ln -s "$dev_path" /dev/disk/by-id/google-persistent-disk-"$ID_SERIAL_SHORT" > /dev/null 2>&1
   fi
 
-  return 0
-}
-
-#######################################
-# Validates that a given path corresponds to a valid NVMe device
-# Globals:
-#   Uses nvme_cli_bin
-# Arguments:
-#   The device path for the disk
-# Returns:
-#   The return value of the call to the nvme id-ctrl command
-#######################################
-function validate_nvme_device() {
-  "${nvme_cli_bin}" id-ctrl "${1}" &>/dev/null
-}
-
-#######################################
-# Determines if the device path is a PD or Local SSD disk
-# Globals:
-#   Uses nvme_cli_bin, PD, and LOCAL_SSD
-# Arguments:
-#   The device path for the disk
-# Returns:
-#   1 if the device type is Unknown, 0 on success
-#######################################
-function detect_pd_or_local_ssd() {
-  local nvme_id_ctrl
-  nvme_id_ctrl="$("${nvme_cli_bin}" id-ctrl "${1}")"
-  if [[ "${nvme_id_ctrl}" =~ 'nvme_card-pd' ]]; then
-    echo "${PD}"
-  elif [[ "${nvme_id_ctrl}" =~ 'nvme_card' ]]; then
-    echo "${LOCAL_SSD}"
-  else
-    return 1
-  fi
   return 0
 }
 
 #######################################
 # Populates the ID_* global variables with a disk's device name and namespace
 # Globals:
-#   Populates ID_NAMESPACE_INDEX, ID_SERIAL_SHORT, and ID_SERIAL
+#   Populates ID_SERIAL_SHORT, and ID_SERIAL
 # Arguments:
 #   The device path for the disk
 # Returns:
 #   0 on success and 255 if an error occurrs
 #######################################
 function identify_pd_disk() {
-  local dev_path="${1}"
+  local dev_path="$1"
   local dev_name
-  dev_name="$(get_namespace_device_name "${dev_path}")"
-  if [[ $? != 0 ]]; then
+  dev_name="$(get_namespace_device_name "$dev_path")"
+  if [[ $? -ne 0 ]]; then
     return 255
   fi
 
-  ID_NAMESPACE_INDEX="${namespace_index}"
-  ID_SERIAL_SHORT="${dev_name}"
+  ID_SERIAL_SHORT="$dev_name"
   ID_SERIAL="Google_PersistentDisk_${ID_SERIAL_SHORT}"
   return 0
-}
-
-#######################################
-# Ensures a given command/path exists
-# Arguments:
-#   The path for the command
-# Returns:
-#   0 if the command is found/executable and 1 on error
-#######################################
-function confirm_command() {
-  local command_to_check="${1}"
-  command -v "${command_to_check}" > /dev/null 2>&1
-  if [[ $? != 0 ]]; then
-    return 1
-  else
-    return 0
-  fi
 }
 
 function print_help_message() {
@@ -236,8 +181,8 @@ function main() {
   local device_path=''
 
   while getopts :d:sh flag; do
-    case "${flag}" in
-      d) device_path="${OPTARG}";;
+    case "$flag" in
+      d) device_path="$OPTARG";;
       s) opt_gen_symlink='true';;
       h) print_help_message
          return 0
@@ -254,47 +199,42 @@ function main() {
     exit 1
   fi
 
-  confirm_command "${nvme_cli_bin}"
-  if [[ $? != 0 ]]; then
-    local err_msg="The nvme utility (/usr/sbin/nvme) was not found."
-    err_msg="${err_msg} You may need to run with sudo or install nvme-cli."
-    err "${err_msg}"
+  # Ensure the nvme-cli command is installed
+  command -v "$nvme_cli_bin" > /dev/null 2>&1
+  if [[ $? -ne 0 ]]; then
+    err "The nvme utility (/usr/sbin/nvme) was not found. You may need to run \
+with sudo or install nvme-cli."
     return 1
   fi
 
   # Ensure the passed device is actually an NVMe device
-  validate_nvme_device "${device_path}"
-  if [[ $? != 0 ]]; then
-    local err_msg="Passed device was not an NVMe device.  (You may need to run"
-    err_msg="${err_msg} this script as root/with sudo)."
-    err "${err_msg}"
+  "$nvme_cli_bin" id-ctrl "$device_path" &>/dev/null
+  if [[ $? -ne 0 ]]; then
+    err "Passed device was not an NVMe device.  (You may need to run this \
+script as root/with sudo)."
     return 1
   fi
 
   # Detect the type of attached nvme device
-  local device_type="$(detect_pd_or_local_ssd "${device_path}")"
-  local device_type_ret_value=$?
-  if [[ "${device_type}" == "${LOCAL_SSD}" ]]; then
-    err "This script only supports PD NVMe disks but given path was Local SSD"
-    return 1
-  elif [[ "${device_type_ret_value}" != 0 ]]; then
-    err "Unknown device type (neither a PD nor Local SSD NVMe device)"
+  local controller_id
+  controller_id=$("$nvme_cli_bin" id-ctrl "$device_path")
+  if [[ ! "$controller_id" =~ nvme_card-pd ]] ; then
+    err "Device is not a PD-NVMe device"
     return 1
   fi
 
   # Fill the global variables for the id command for the given disk type
-  identify_pd_disk "${device_path}"
-  identify_ret_value=$?
-
   # Error messages will be printed closer to error, no need to reprint here
-  if [[ "${identify_ret_value}" != 0 ]]; then
-    return "${identify_ret_value}"
+  identify_pd_disk "$device_path"
+  if [[ $? -ne 0 ]]; then
+    return $?
   fi
 
   # Gen symlinks or print out the globals set by the identify command
-  if [[ "${opt_gen_symlink}" == 'true' ]]; then
-    gen_symlink "${device_path}"
+  if [[ "$opt_gen_symlink" == 'true' ]]; then
+    gen_symlink "$device_path"
   else
+    # These will be consumed by udev
     echo "ID_SERIAL_SHORT=${ID_SERIAL_SHORT}"
     echo "ID_SERIAL=${ID_SERIAL}"
   fi
